import {
  Organization,
  User,
  OrganizationMember,
  Workflow,
  WorkflowRun,
  StepExecution,
  Event,
  Integration,
  ApiKey,
  AuditLog,
  Notification,
  DashboardStats,
  Invitation,
} from "./types";

const now = Date.now();
const hour = 3600000;
const day = 86400000;

export const mockUsers: User[] = [
  {
    _id: "user_1",
    externalId: "clerk_user_1",
    email: "alex@acme.com",
    name: "Alex Chen",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    createdAt: now - 90 * day,
    updatedAt: now - day,
  },
  {
    _id: "user_2",
    externalId: "clerk_user_2",
    email: "sarah@acme.com",
    name: "Sarah Miller",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    createdAt: now - 60 * day,
    updatedAt: now - 2 * day,
  },
  {
    _id: "user_3",
    externalId: "clerk_user_3",
    email: "james@acme.com",
    name: "James Wilson",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=james",
    createdAt: now - 30 * day,
    updatedAt: now - 5 * day,
  },
];

export const mockOrganizations: Organization[] = [
  {
    _id: "org_1",
    name: "Acme Corp",
    slug: "acme-corp",
    plan: "pro",
    billingEmail: "billing@acme.com",
    usageLimitExecutions: 10000,
    usageCurrentExecutions: 4523,
    usageResetAt: now + 15 * day,
    settings: {
      defaultRetryPolicy: {
        maxAttempts: 3,
        backoffCoefficient: 2,
        initialInterval: 1000,
        maxInterval: 60000,
      },
      alertEmails: ["alex@acme.com", "ops@acme.com"],
    },
    createdAt: now - 90 * day,
    updatedAt: now - day,
  },
  {
    _id: "org_2",
    name: "Startup Inc",
    slug: "startup-inc",
    plan: "free",
    usageLimitExecutions: 1000,
    usageCurrentExecutions: 234,
    usageResetAt: now + 20 * day,
    settings: {
      defaultRetryPolicy: {
        maxAttempts: 3,
        backoffCoefficient: 2,
        initialInterval: 1000,
        maxInterval: 60000,
      },
      alertEmails: [],
    },
    createdAt: now - 30 * day,
    updatedAt: now - 7 * day,
  },
];

export const mockMembers: OrganizationMember[] = [
  {
    _id: "member_1",
    organizationId: "org_1",
    userId: "user_1",
    user: mockUsers[0],
    role: "owner",
    joinedAt: now - 90 * day,
  },
  {
    _id: "member_2",
    organizationId: "org_1",
    userId: "user_2",
    user: mockUsers[1],
    role: "admin",
    invitedBy: "user_1",
    joinedAt: now - 60 * day,
  },
  {
    _id: "member_3",
    organizationId: "org_1",
    userId: "user_3",
    user: mockUsers[2],
    role: "member",
    invitedBy: "user_1",
    joinedAt: now - 30 * day,
  },
];

export const mockInvitations: Invitation[] = [
  {
    _id: "inv_1",
    organizationId: "org_1",
    email: "newdev@acme.com",
    role: "member",
    invitedBy: "user_1",
    token: "inv_token_abc123",
    expiresAt: now + 7 * day,
    status: "pending",
    createdAt: now - 2 * day,
  },
];

export const mockWorkflows: Workflow[] = [
  {
    _id: "wf_1",
    organizationId: "org_1",
    name: "Lead Enrichment",
    slug: "lead-enrichment",
    description: "Enriches new leads from Salesforce with company data and assigns to sales reps",
    trigger: { type: "webhook", config: { path: "/webhooks/salesforce/lead" } },
    steps: [
      { id: "step_1", name: "Fetch Company Data", type: "action", config: { service: "clearbit" } },
      { id: "step_2", name: "Score Lead", type: "action", config: { service: "internal" } },
      { id: "step_3", name: "Assign Rep", type: "condition", config: { field: "score" } },
      { id: "step_4", name: "Notify Slack", type: "action", config: { channel: "#sales" } },
    ],
    status: "active",
    version: 3,
    createdBy: "user_1",
    updatedBy: "user_2",
    createdAt: now - 45 * day,
    updatedAt: now - 2 * day,
    lastRunAt: now - hour,
    lastRunStatus: "completed",
    runCount7Days: 156,
  },
  {
    _id: "wf_2",
    organizationId: "org_1",
    name: "Order Fulfillment",
    slug: "order-fulfillment",
    description: "Processes new orders from Stripe and triggers shipping workflow",
    trigger: { type: "event", config: { eventType: "order.created" } },
    steps: [
      { id: "step_1", name: "Validate Inventory", type: "action", config: {} },
      { id: "step_2", name: "Create Shipment", type: "action", config: { provider: "shippo" } },
      { id: "step_3", name: "Update Order Status", type: "action", config: {} },
      { id: "step_4", name: "Send Confirmation", type: "action", config: { template: "order_shipped" } },
    ],
    status: "active",
    version: 5,
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: now - 60 * day,
    updatedAt: now - 5 * day,
    lastRunAt: now - 30 * 60000,
    lastRunStatus: "completed",
    runCount7Days: 423,
  },
  {
    _id: "wf_3",
    organizationId: "org_1",
    name: "Daily Report Generator",
    slug: "daily-report",
    description: "Generates and emails daily analytics report",
    trigger: { type: "schedule", config: { cron: "0 8 * * *" } },
    steps: [
      { id: "step_1", name: "Fetch Analytics", type: "action", config: {} },
      { id: "step_2", name: "Generate PDF", type: "action", config: {} },
      { id: "step_3", name: "Send Email", type: "action", config: { to: "team@acme.com" } },
    ],
    status: "active",
    version: 2,
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: now - 20 * day,
    updatedAt: now - 10 * day,
    lastRunAt: now - 16 * hour,
    lastRunStatus: "completed",
    runCount7Days: 7,
  },
  {
    _id: "wf_4",
    organizationId: "org_1",
    name: "Customer Churn Alert",
    slug: "churn-alert",
    description: "Monitors customer activity and alerts on potential churn",
    trigger: { type: "event", config: { eventType: "customer.inactive" } },
    steps: [
      { id: "step_1", name: "Check Activity", type: "action", config: {} },
      { id: "step_2", name: "Calculate Risk Score", type: "action", config: {} },
      { id: "step_3", name: "High Risk?", type: "condition", config: { threshold: 0.7 } },
      { id: "step_4", name: "Alert CSM", type: "action", config: { channel: "#customer-success" } },
    ],
    status: "paused",
    version: 1,
    createdBy: "user_3",
    updatedBy: "user_3",
    createdAt: now - 10 * day,
    updatedAt: now - 3 * day,
    lastRunAt: now - 3 * day,
    lastRunStatus: "failed",
    runCount7Days: 0,
  },
  {
    _id: "wf_5",
    organizationId: "org_1",
    name: "GitHub Issue Triage",
    slug: "github-triage",
    description: "Auto-labels and assigns new GitHub issues",
    trigger: { type: "webhook", config: { path: "/webhooks/github/issues" } },
    steps: [
      { id: "step_1", name: "Analyze Issue", type: "action", config: { model: "gpt-4" } },
      { id: "step_2", name: "Add Labels", type: "action", config: {} },
      { id: "step_3", name: "Assign Owner", type: "action", config: {} },
    ],
    status: "draft",
    version: 1,
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: now - 2 * day,
    updatedAt: now - 2 * day,
    runCount7Days: 0,
  },
];

export const mockWorkflowRuns: WorkflowRun[] = [
  {
    _id: "run_1",
    organizationId: "org_1",
    workflowId: "wf_1",
    workflow: mockWorkflows[0],
    workflowVersion: 3,
    status: "completed",
    triggerType: "webhook",
    triggerData: { lead_id: "lead_12345", email: "john@example.com" },
    result: { assigned_to: "rep_42", score: 85 },
    startedAt: now - hour,
    completedAt: now - hour + 2500,
    durationMs: 2500,
    createdAt: now - hour,
  },
  {
    _id: "run_2",
    organizationId: "org_1",
    workflowId: "wf_2",
    workflow: mockWorkflows[1],
    workflowVersion: 5,
    status: "running",
    triggerType: "event",
    triggerData: { order_id: "ord_98765", amount: 299.99 },
    startedAt: now - 45000,
    createdAt: now - 45000,
  },
  {
    _id: "run_3",
    organizationId: "org_1",
    workflowId: "wf_1",
    workflow: mockWorkflows[0],
    workflowVersion: 3,
    status: "failed",
    triggerType: "webhook",
    triggerData: { lead_id: "lead_67890", email: "invalid" },
    error: {
      message: "Failed to enrich lead: Invalid email format",
      stack: "Error: Invalid email format\n    at enrichLead (/workflow/steps.ts:42:11)",
      stepId: "step_1",
    },
    startedAt: now - 2 * hour,
    completedAt: now - 2 * hour + 1200,
    durationMs: 1200,
    createdAt: now - 2 * hour,
  },
  {
    _id: "run_4",
    organizationId: "org_1",
    workflowId: "wf_3",
    workflow: mockWorkflows[2],
    workflowVersion: 2,
    status: "completed",
    triggerType: "schedule",
    triggerData: { scheduled_time: now - 16 * hour },
    result: { report_url: "https://storage.orbin.dev/reports/daily_2024-01-15.pdf" },
    startedAt: now - 16 * hour,
    completedAt: now - 16 * hour + 45000,
    durationMs: 45000,
    createdAt: now - 16 * hour,
  },
  {
    _id: "run_5",
    organizationId: "org_1",
    workflowId: "wf_4",
    workflow: mockWorkflows[3],
    workflowVersion: 1,
    status: "failed",
    triggerType: "event",
    triggerData: { customer_id: "cust_555" },
    error: {
      message: "API rate limit exceeded",
      stepId: "step_2",
    },
    startedAt: now - 3 * day,
    completedAt: now - 3 * day + 5000,
    durationMs: 5000,
    createdAt: now - 3 * day,
  },
  {
    _id: "run_6",
    organizationId: "org_1",
    workflowId: "wf_2",
    workflow: mockWorkflows[1],
    workflowVersion: 5,
    status: "pending",
    triggerType: "event",
    triggerData: { order_id: "ord_11111", amount: 149.99 },
    createdAt: now - 5000,
  },
];

export const mockStepExecutions: StepExecution[] = [
  {
    _id: "step_exec_1",
    organizationId: "org_1",
    workflowRunId: "run_2",
    stepId: "step_1",
    stepName: "Validate Inventory",
    status: "completed",
    attempt: 1,
    maxAttempts: 3,
    input: { order_id: "ord_98765", items: ["sku_123", "sku_456"] },
    output: { available: true, warehouse: "us-west-2" },
    startedAt: now - 45000,
    completedAt: now - 43000,
    durationMs: 2000,
    createdAt: now - 45000,
  },
  {
    _id: "step_exec_2",
    organizationId: "org_1",
    workflowRunId: "run_2",
    stepId: "step_2",
    stepName: "Create Shipment",
    status: "running",
    attempt: 1,
    maxAttempts: 3,
    input: { warehouse: "us-west-2", items: ["sku_123", "sku_456"] },
    startedAt: now - 43000,
    createdAt: now - 43000,
  },
  {
    _id: "step_exec_3",
    organizationId: "org_1",
    workflowRunId: "run_2",
    stepId: "step_3",
    stepName: "Update Order Status",
    status: "pending",
    attempt: 0,
    maxAttempts: 3,
    createdAt: now - 45000,
  },
  {
    _id: "step_exec_4",
    organizationId: "org_1",
    workflowRunId: "run_2",
    stepId: "step_4",
    stepName: "Send Confirmation",
    status: "pending",
    attempt: 0,
    maxAttempts: 3,
    createdAt: now - 45000,
  },
  {
    _id: "step_exec_5",
    organizationId: "org_1",
    workflowRunId: "run_3",
    stepId: "step_1",
    stepName: "Fetch Company Data",
    status: "failed",
    attempt: 3,
    maxAttempts: 3,
    input: { email: "invalid" },
    error: {
      message: "Invalid email format",
      stack: "Error: Invalid email format\n    at validateEmail (/lib/email.ts:15:9)",
    },
    startedAt: now - 2 * hour,
    completedAt: now - 2 * hour + 1200,
    durationMs: 1200,
    createdAt: now - 2 * hour,
  },
];

export const mockEvents: Event[] = [
  {
    _id: "evt_1",
    organizationId: "org_1",
    eventType: "lead.created",
    eventId: "sf_evt_123",
    source: "salesforce",
    payload: { lead_id: "lead_12345", email: "john@example.com", company: "Example Inc" },
    processedAt: now - hour,
    status: "processed",
    createdAt: now - hour - 100,
  },
  {
    _id: "evt_2",
    organizationId: "org_1",
    eventType: "order.created",
    eventId: "stripe_evt_456",
    source: "stripe",
    payload: { order_id: "ord_98765", amount: 299.99, customer: "cust_789" },
    status: "pending",
    createdAt: now - 45000,
  },
  {
    _id: "evt_3",
    organizationId: "org_1",
    eventType: "customer.inactive",
    eventId: "internal_evt_789",
    source: "analytics",
    payload: { customer_id: "cust_555", days_inactive: 30 },
    processedAt: now - 3 * day,
    status: "failed",
    createdAt: now - 3 * day,
  },
  {
    _id: "evt_4",
    organizationId: "org_1",
    eventType: "order.created",
    eventId: "stripe_evt_111",
    source: "stripe",
    payload: { order_id: "ord_11111", amount: 149.99 },
    status: "pending",
    createdAt: now - 5000,
  },
];

export const mockIntegrations: Integration[] = [
  {
    _id: "int_1",
    organizationId: "org_1",
    provider: "slack",
    name: "Acme Slack Workspace",
    credentials: "encrypted_oauth_token",
    config: { default_channel: "#general" },
    status: "active",
    lastSyncAt: now - 5 * 60000,
    connectedBy: "user_1",
    connectedByUser: mockUsers[0],
    createdAt: now - 60 * day,
    updatedAt: now - 5 * 60000,
  },
  {
    _id: "int_2",
    organizationId: "org_1",
    provider: "github",
    name: "acme-corp",
    credentials: "encrypted_github_token",
    config: { repos: ["acme-corp/main-app", "acme-corp/api"] },
    status: "active",
    lastSyncAt: now - hour,
    connectedBy: "user_2",
    connectedByUser: mockUsers[1],
    createdAt: now - 45 * day,
    updatedAt: now - hour,
  },
  {
    _id: "int_3",
    organizationId: "org_1",
    provider: "salesforce",
    name: "Acme Salesforce",
    credentials: "encrypted_sf_token",
    status: "error",
    lastSyncAt: now - 2 * day,
    connectedBy: "user_1",
    connectedByUser: mockUsers[0],
    createdAt: now - 90 * day,
    updatedAt: now - 2 * day,
  },
  {
    _id: "int_4",
    organizationId: "org_1",
    provider: "stripe",
    name: "Stripe Production",
    credentials: "encrypted_stripe_key",
    status: "active",
    lastSyncAt: now - 30 * 60000,
    connectedBy: "user_1",
    connectedByUser: mockUsers[0],
    createdAt: now - 80 * day,
    updatedAt: now - 30 * 60000,
  },
];

export const mockApiKeys: ApiKey[] = [
  {
    _id: "key_1",
    organizationId: "org_1",
    name: "Production API Key",
    type: "secret",
    keyPrefix: "sk_live_",
    keyHash: "sha256_hash_1",
    lastFourChars: "x7Kp",
    lastUsedAt: now - 5 * 60000,
    createdBy: "user_1",
    createdByUser: mockUsers[0],
    createdAt: now - 60 * day,
  },
  {
    _id: "key_2",
    organizationId: "org_1",
    name: "CI/CD Pipeline",
    type: "secret",
    keyPrefix: "sk_live_",
    keyHash: "sha256_hash_2",
    lastFourChars: "mN3q",
    lastUsedAt: now - hour,
    createdBy: "user_2",
    createdByUser: mockUsers[1],
    createdAt: now - 30 * day,
  },
  {
    _id: "key_3",
    organizationId: "org_1",
    name: "Frontend Widget",
    type: "publishable",
    keyPrefix: "pk_live_",
    keyHash: "sha256_hash_3",
    lastFourChars: "aB2c",
    lastUsedAt: now - 10 * 60000,
    createdBy: "user_1",
    createdByUser: mockUsers[0],
    createdAt: now - 45 * day,
  },
  {
    _id: "key_4",
    organizationId: "org_1",
    name: "Read-Only Analytics",
    type: "restricted",
    keyPrefix: "rk_live_",
    keyHash: "sha256_hash_4",
    lastFourChars: "zY9w",
    permissions: ["workflows:read", "runs:read", "events:read"],
    createdBy: "user_3",
    createdByUser: mockUsers[2],
    createdAt: now - 10 * day,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    _id: "audit_1",
    organizationId: "org_1",
    actorId: "user_1",
    actor: mockUsers[0],
    actorType: "user",
    action: "workflow.updated",
    resourceType: "workflow",
    resourceId: "wf_1",
    metadata: { changes: ["steps", "version"] },
    ipAddress: "192.168.1.1",
    createdAt: now - 2 * day,
  },
  {
    _id: "audit_2",
    organizationId: "org_1",
    actorId: "user_2",
    actor: mockUsers[1],
    actorType: "user",
    action: "member.invited",
    resourceType: "invitation",
    resourceId: "inv_1",
    metadata: { email: "newdev@acme.com", role: "member" },
    ipAddress: "192.168.1.2",
    createdAt: now - 2 * day,
  },
  {
    _id: "audit_3",
    organizationId: "org_1",
    actorType: "system",
    action: "workflow.executed",
    resourceType: "workflowRun",
    resourceId: "run_1",
    metadata: { trigger: "webhook", duration_ms: 2500 },
    createdAt: now - hour,
  },
  {
    _id: "audit_4",
    organizationId: "org_1",
    actorType: "api",
    action: "event.ingested",
    resourceType: "event",
    resourceId: "evt_1",
    metadata: { event_type: "lead.created", source: "salesforce" },
    createdAt: now - hour,
  },
  {
    _id: "audit_5",
    organizationId: "org_1",
    actorId: "user_3",
    actor: mockUsers[2],
    actorType: "user",
    action: "apiKey.created",
    resourceType: "apiKey",
    resourceId: "key_4",
    metadata: { name: "Read-Only Analytics", type: "restricted" },
    ipAddress: "192.168.1.3",
    createdAt: now - 10 * day,
  },
];

export const mockNotifications: Notification[] = [
  {
    _id: "notif_1",
    userId: "user_1",
    organizationId: "org_1",
    type: "workflow_failed",
    title: "Workflow Failed",
    message: "Lead Enrichment workflow failed: Invalid email format",
    link: "/acme-corp/runs/run_3",
    read: false,
    createdAt: now - 2 * hour,
  },
  {
    _id: "notif_2",
    userId: "user_1",
    organizationId: "org_1",
    type: "usage_threshold",
    title: "Usage Alert",
    message: "You've used 45% of your monthly execution quota",
    link: "/acme-corp/settings/billing",
    read: true,
    createdAt: now - 2 * day,
  },
  {
    _id: "notif_3",
    userId: "user_1",
    organizationId: "org_1",
    type: "member_joined",
    title: "New Team Member",
    message: "James Wilson joined the organization",
    link: "/acme-corp/settings/members",
    read: true,
    createdAt: now - 30 * day,
  },
  {
    _id: "notif_4",
    userId: "user_1",
    organizationId: "org_1",
    type: "integration_error",
    title: "Integration Error",
    message: "Salesforce connection failed. Please re-authenticate.",
    link: "/acme-corp/integrations/salesforce",
    read: false,
    createdAt: now - 2 * day,
  },
];

export const mockDashboardStats: DashboardStats = {
  executionsToday: 127,
  executionsThisMonth: 4523,
  executionLimit: 10000,
  successRate: 98.2,
  avgLatencyMs: 1850,
  activeWorkflows: 3,
  runningNow: 1,
  failedLast24h: 2,
  completedLast24h: 125,
};

export function getCurrentUser(): User {
  return mockUsers[0];
}

export function getCurrentOrganization(): Organization {
  return mockOrganizations[0];
}
